---
# installation du paquet mariadb-server
- name: mariadb server installation
  apt:
     name: mariadb-server
     state: latest

# Active le service mariadb
- name: start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
