---

- name: Display and get config
  gather_facts: True
  hosts: all
 
  tasks:

  - name: Display the config

    debug:
      msg: OS version = {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}
