---

#. Cette tâche installe PHP7 et ses extensions
- name: install php7.4 packages
  apt:
    name: php,php-mysql,php-xml,php-mbstring,libmcrypt4,libtomcrypt1,mcrypt,php-gd,php-intl
    state: latest
  changed_when: yes
  notify: [ apache restart ]
